### ISSUE TITLE
Downloader archive validation not complete

### ISSUE THREAD

**Issue by BobBall** [xenserver/buildroot#575]
00:18:00.289 curl: (18) transfer closed with 9715648 bytes remaining to read
00:18:00.290 Downloading http://www.infradead.org/~tgr/libnl/files/libnl-doc-3.2.22.tar.gz failed: sleeping 5s
00:18:05.298 ./SOURCES/libnl-doc-3.2.22.tar.gz exists and looks like an archive

The build then later fails, clearly.  Possibly delete the file if curl returns non zero exit?

**Comment by euanh** [comment]
Superseded by the new planex-fetch command.
