### ISSUE TITLE
stunnel does not restart

### ISSUE THREAD

**Issue by BobBall** [xenserver/buildroot#611]
Probably during an upgrade, but stunnel fails to restart because

 [root@vogsphere ~]# stunnel /etc/xapi/xapissl.conf
 2015.01.29 15:40:37 LOG7[3446:140204308850624]: RAND_status claims sufficient entropy for the PRNG
 2015.01.29 15:40:37 LOG7[3446:140204308850624]: PRNG seeded successfully
 2015.01.29 15:40:37 LOG7[3446:140204308850624]: Certificate: /etc/xapi/ssl.pem
 2015.01.29 15:40:37 LOG7[3446:140204308850624]: Certificate loaded
 2015.01.29 15:40:37 LOG7[3446:140204308850624]: Key file: /etc/xapi/ssl.pem
 2015.01.29 15:40:37 LOG7[3446:140204308850624]: Private key loaded
 2015.01.29 15:40:37 LOG7[3446:140204308850624]: SSL context initialized for service xapi
 2015.01.29 15:40:37 LOG3[3446:140204308850624]: FIPS_mode_set: 2D06C06E: error:2D06C06E:FIPS routines:FIPS_module_mode_set:fingerprint does not match

Fix seems to be to add "fips = no" in ssl config

**Comment by djs55** [comment]
Did this not fix it?

https://github.com/xenserver/buildroot/pull/609


On Thu, Jan 29, 2015 at 3:37 PM, Bob Ball <notifications@github.com> wrote:

> Probably during an upgrade, but stunnel fails to restart because
>
> [root@vogsphere ~]# stunnel /etc/xapi/xapissl.conf
> 2015.01.29 15:40:37 LOG7[3446:140204308850624]: RAND_status claims
> sufficient entropy for the PRNG
> 2015.01.29 15:40:37 LOG7[3446:140204308850624]: PRNG seeded successfully
> 2015.01.29 15:40:37 LOG7[3446:140204308850624]: Certificate:
> /etc/xapi/ssl.pem
> 2015.01.29 15:40:37 LOG7[3446:140204308850624]: Certificate loaded
> 2015.01.29 15:40:37 LOG7[3446:140204308850624]: Key file: /etc/xapi/ssl.pem
> 2015.01.29 15:40:37 LOG7[3446:140204308850624]: Private key loaded
> 2015.01.29 15:40:37 LOG7[3446:140204308850624]: SSL context initialized
> for service xapi
> 2015.01.29 15:40:37 LOG3[3446:140204308850624]: FIPS_mode_set: 2D06C06E:
> error:2D06C06E:FIPS routines:FIPS_module_mode_set:fingerprint does not match
>
> Fix seems to be to add "fips = no" in ssl config
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xenserver/buildroot/issues/611>.
>



-- 
Dave Scott

**Comment by BobBall** [comment]
Almost certainly.  The test server I was using was built overnight and I didn't spot this change which only went in today :)

**Comment by djs55** [comment]
Ah phew, I thought there was direct evidence that my patch was bad :)

On Thursday, January 29, 2015, Bob Ball <notifications@github.com> wrote:

> Almost certainly. The test server I was using was built overnight and I
> didn't spot this change which only went in today :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xenserver/buildroot/issues/611#issuecomment-72060671>.
>


-- 
Dave Scott
