### ISSUE TITLE
CentOS 6.6 make failed

### ISSUE THREAD

**Issue by vadimkim** [xenserver/buildroot#620]
Script failed with the following error just in the beginning:
deps:1370: warning: overriding commands for target `SOURCES/mirage-1.2.0.tar.gz'
deps:1009: warning: ignoring old commands for target `SOURCES/mirage-1.2.0.tar.gz'
[MOCK] RPMS/x86_64/ocaml-ounit-2.0.0-1.el6.x86_64.rpm
ERROR: Exception(SRPMS/ocaml-ounit-2.0.0-1.el6.src.rpm) Config(epel-6-x86_64) 0 minutes 9 seconds
ERROR: Command failed. See logs for output.
 # /usr/bin/yum --installroot /var/lib/mock/epel-6-x86_64-ocaml-ounit-2.0.0-1.el6.x86_64.rpm/root/ groupinstall buildsys-build --setopt=tsflags=nocontexts
make: *** [RPMS/x86_64/ocaml-ounit-2.0.0-1.el6.x86_64.rpm] Error 1

root.log file shows that while installing some extra packages there is no space at / filesystem:
DEBUG util.py:366:  Install     143 Package(s)
DEBUG util.py:366:  Total size: 104 M
DEBUG util.py:366:  Installed size: 375 M
DEBUG util.py:366:  Transaction Check Error:
DEBUG util.py:366:    installing package glibc-common-2.12-1.149.el6_6.5.x86_64 needs 29MB on the / filesystem
DEBUG util.py:366:    installing package xz-lzma-compat-4.999.9-0.5.beta.20091007git.el6.x86_64 needs 29MB on the / filesystem
DEBUG util.py:366:    installing package cracklib-dicts-2.8.16-4.el6.x86_64 needs 38MB on the / filesystem
DEBUG util.py:366:    installing package centos-release-6-6.el6.centos.12.2.x86_64 needs 38MB on the / filesystem
DEBUG util.py:366:    installing package libutempter-1.1.5-4.1.el6.x86_64 needs 38MB on the / filesystem
DEBUG util.py:366:    installing package libsemanage-2.0.43-4.2.el6.x86_64 needs 39MB on the / filesystem
DEBUG util.py:366:    installing package chkconfig-1.3.49.3-2.el6_4.1.x86_64 needs 39MB on the / filesystem
DEBUG util.py:366:    installing package iputils-20071127-17.el6_4.2.x86_64 needs 40MB on the / filesystem
DEBUG util.py:366:    installing package glibc-devel-2.12-1.149.el6_6.5.x86_64 needs 41MB on the / filesystem
DEBUG util.py:366:    installing package gzip-1.3.12-22.el6.x86_64 needs 41MB on the / filesystem
DEBUG util.py:366:    installing package mingetty-1.08-5.el6.x86_64 needs 41MB on the / filesystem
DEBUG util.py:366:    installing package findutils-1:4.4.2-6.el6.x86_64 needs 43MB on the / filesystem
DEBUG util.py:366:    installing package sysvinit-tools-2.87-5.dsf.el6.x86_64 needs 43MB on the / filesystem
DEBUG util.py:366:  Error Summary
DEBUG util.py:366:  -------------
DEBUG util.py:366:  Disk Requirements:
DEBUG util.py:366:    At least 43MB more space needed on the / filesystem.

There is 45Gb free space at root.

**Comment by scpcom** [comment]
The error does not refer to real root. By default mock builts xenserver-core inside RAM, I think 6GB schould be the minimum.

An alternate way is to edit the file
/etc/mock/site-defaults.cfg

you can force to use harddisk instead of RAM by adding a line like this:

config_opts['plugin_conf']['bind_mount_opts']['dirs'].append(('/host/path/build', '/build/' ))

Then you have to create an empty directory (/host/path/build in this example).

**Comment by vadimkim** [comment]
Hello scpcom,
  Thank you for tips. I still have the same error. I guess the reason may be due to dom0 has already been installed. Please, confirm that I did right things
1. Install clean CentOS 6.6
2. Updated to latest with yum update
3. Install XEN hypervisor as of here: http://wiki.centos.org/HowTos/Xen/Xen4QuickStart
4. Rebooted into XEN
5. Installed ocaml-* libraries from repository ( yum install ocaml ocaml-docs ocaml-camlp4 ocalm-camlp4-devel ocaml-findlib ocaml-findlib-devel)
6. Followed instructions to buildroot.

**Comment by vadimkim** [comment]
I have done it in a wrong way. The only dependency I need to install is git. XEN and OCAML buildroot does by itself. So I got it installed without any problems.
