### ISSUE TITLE
Is this building correctly on Ubuntu 14.04

### ISSUE THREAD

**Issue by mjb2000** [xenserver/buildroot#653]
I have been trying in vain to get a working install of Xen + XAPI on either Debian or Ubuntu, so this project seemed to offer a solution, but I have not been able to get this project to build and I've experienced similar errors to those reported in other issues.

If anyone can offer some tips on the steps required to get a successful build from a clean base-system install of Ubuntu 14.04 then I'd really appreciate it!

So far I have tried installing the following packages before trying to build using the steps described in the readme.

If I'm missing something, or if anyone has any tips I'd really appreciate it!

```
apt-get install git-core ocaml ocaml-native-compilers camplp4-extra libre-ocaml-dev cowbuilder createrepo python-pip
pip install argcomplete
```

**Comment by inigoml** [comment]
I tried to compile first in Ubuntu 14.04. No luck. Then, I switched to CentOS 6.6. I sucessfully compiled Xenserver but plenty problems when installing.
I'm afraid there are a lot of bugs yet and this project seems to be a bit "dead"... probably Citrix staff is working in a parallel project outside community.

**Comment by mjb2000** [comment]
Hi @inigoml - Thanks for replying. At least now I know I can give up on this!

I will take a closer look at Xen + Libvirt for now :)
